[cursor]
blink_interval = 450

[cursor.style]
blinking = "never"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 17.5

## MonoLisa,JetBrainsMono,Berkeley Mono
[font.normal]
family = "Berkeley Mono"
style = "Regular"

[font.bold]
family = "Berkeley Mono"
style = "Bold"

[font.bold_italic]
family = "Berkeley Mono"
style = "Bold Italic"

[font.italic]
family = "Berkeley Mono"
style = "Italic"


[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[window]
decorations = "none"
opacity = 1

## ROSE PINE

[colors.primary]
# 191724,181622
background = "#181622"
foreground = "#e0def4"

[colors.bright]
black = "#565656"
blue = "#49a4f8"
cyan = "#99faf2"
green = "#c0e17d"
magenta = "#a47de9"
red = "#ec5357"
white = "#ffffff"
yellow = "#f9da6a"

[colors.cursor]
cursor = "#e0def4"
text = "#121212"

[colors.normal]
black = "#121212"
blue = "#47a0f3"
cyan = "#64dbed"
green = "#abe047"
magenta = "#7b5cb0"
red = "#eb4129"
white = "#e5e9f0"
yellow = "#f6c744"
