## iTerm Default ####################
[colors.primary]
# 0d1117,171521,191724,0b0e14
background = "#151515"
foreground = "#fffbf6"

[colors.cursor]
#fffbf6,f8f8f2,d9d9c4
text = "#6e6a86"
cursor = "#d9d9c4"

[colors.normal]
black = "#2e2e2e"
red = "#eb4129"
green = "#abe047"
yellow = "#f6c744"
blue = "#47a0f3"
magenta = "#7b5cb0"
cyan = "#64dbed"
white = "#e5e9f0"

[colors.bright]
black = "#565656"
red = "#ec5357"
green = "#c0e17d"
yellow = "#f9da6a"
blue = "#49a4f8"
magenta = "#a47de9"
cyan = "#99faf2"
white = "#ffffff"

########################################
# SETTINGS
########################################
[cursor]
blink_interval = 500

[cursor.style]
blinking = "always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
# MonoLssa 15.5,16.88,18
# Berkele 18,18.4
size = 18

## MonoLisa,JetBrainsMono,Berkeley Mono
[font.normal]
family = "Berkeley Mono"
style = "Regular"

[font.bold]
family = "Berkeley Mono"
style = "Bold"

[font.bold_italic]
family = "Berkeley Mono"
style = "Bold Italic"

[font.italic]
family = "Berkeley Mono"
style = "Italic"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[window]
decorations = "none"
opacity = 1
