## iTerm Default ####################
[colors.primary]
# 0b0e14,1f2430,13121c,171521,191724
background = "#191724"
foreground = "#fffbf6"

[colors.cursor]
#6e6a86,e6edf3
#f6c177
text = "#6e6a86"
cursor = "#e6edf3"

[colors.normal]
black = "#2e2e2e"
red = "#eb4129"
green = "#abe047"
yellow = "#f6c744"
blue = "#47a0f3"
magenta = "#7b5cb0"
cyan = "#64dbed"
white = "#e5e9f0"

[colors.bright]
black = "#565656"
red = "#ec5357"
green = "#c0e17d"
yellow = "#f9da6a"
blue = "#49a4f8"
magenta = "#a47de9"
cyan = "#99faf2"
white = "#ffffff"

########################################
# SETTINGS
########################################
[cursor]
blink_interval = 500

[cursor.style]
blinking = "never"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
# MonoLisa 15.5,16.88,18
# Berkele 17.33,18,18.4
size = 15.5

## MonoLisa,JetBrainsMono,Berkeley Mono
[font.normal]
family = "MonoLisa"
style = "Regular"

[font.bold]
family = "MonoLisa"
style = "Bold"

[font.bold_italic]
family = "MonoLisa"
style = "Bold Italic"

[font.italic]
family = "MonoLisa"
style = "Italic"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[window]
decorations = "none"
opacity = 1
